export const types = {
  ACTUALIZAR_ENTRENADOR: 'ACTUALIZAR_ENTRENADOR',
  ACTUALIZAR_APELLIDO: 'ACTUALIZAR_APELLIDO',
  ACTUALIZAR_EMAIL: 'ACTUALIZAR_EMAIL',
  ACTUALIZAR_POKEMON: 'ACTUALIZAR_POKEMON',
  ACTUALIZAR_TIPO: 'ACTUALIZAR_TIPO',
  ACTUALIZAR_ELEMENTO: 'ACTUALIZAR_ELEMENTO',
  ACTUALIZAR_ALTURA: 'ACTUALIZAR_ALTURA',
  ACTUALIZAR_EDAD: 'ACTUALIZAR_EDAD', 
};
